@startuml TE_Cloud
"VM Module" -> "VM Method": Create & Delete & Update & Retrieve VM Method
note left
    VM Operation method
    (1) Create method
    (2) Delete method
    (3) Update method
    (4) Retrieve method
end note
"VM Server" <- "VM Method": Create & Delete & Update & Retrieve Request API
note left
    VM Operation API
    (1) Create API
    (2) Delete API
    (3) Update API
    (4) Retrieve API
end note
"VM Method" <-- "VM Server": Return Success & Error Status message
"Send Mail Application" <- "VM Method": Send Success infomation & Error information
note left
    VM Status Infomation
    Success & Error
end note
note right
    Type Error (Uesr Error & System Error)
    (1) VM_NOT_CREATED
    (2) VM_NOT_TERMINATED
    (3) VM_NOT_STARTED
    (4) VM_NOT_STOPPED
    (5) VM_NOT_CHECKED
end note

@enduml